### ISSUE TITLE
Hamburger menu disappears after moving mouse under first item.

### ISSUE THREAD

**Issue by AlexKautz** [eliottvincent/bay#1]
To replicate: 

1. Open https://eliottvincent.github.io/bay/ on desktop web browser (Chrome).
2. Resize the window until the top bar collapses into a hamburger menu
3. Click on the hamburger menu to expand it, then slowly move your mouse to click on the third option.
3. The menu will disappear before your mouse reaches it.

**Comment by Speedy905** [comment]
I can replicate this as well (Desktop and Mobile). On Mobile, you press an item, and the menu disappears.

**Comment by eliottvincent** [comment]
Hey guys, thanks for opening the issue. I was able to replicate it too.
I'll fix it during the following days :)
