### ISSUE TITLE
Boldface not applied

### ISSUE THREAD

**Issue by vischia** [eliottvincent/bay#21]
Hello,

I am building my website locally before pushing to github. In the markdown pages (e.g. `index.markdown`) boldface text (either with `**text**` or `__text__`) is not rendered as boldface. Weirdly enough, italics (both `*text*` and `_text_`) is rendered correctly as italics text.

If I use another theme (e.g. `minima`), boldface text is displayed correctly, so I think the issue must come from the `bay` theme sourcecode.

I thought maybe boldface was suppressed by some `text-decoration` or `text-transform` statement, so I digged into the various scss files of the theme, but I could not find anything.

Do you have any hint on how to solve this, to display correctly boldface text with `bay`?

Thank you very much in advance!

**Comment by eliottvincent** [comment]
Hey @vischia , that's an odd behavior.

I hope to find some time to investigate this issue in the coming days. I'll let you know!

**Comment by vischia** [comment]
Hi @eliottvincent , it turns out it happens with Firefox 106.0 (64-bit). With Safari 16.0 the boldface text is displayed correctly.

If I look at the source of the served page, the boldface text is enclosed correctly within a `<strong></strong>` HTML tag. 

At this point I think it's safe to assume it's an issue of Firefox that is not rendering the `<strong></strong>` tag correctly.

If there was a way to force the correct behaviour on Firefox serverside, then it would be fantastic. Otherwise, I guess I'll just google around to see if there is any Firefox setting that overrides the HTML tag, and in this scenario this issue could be closed.

**Comment by eliottvincent** [comment]
Hey! Thanks for taking the time to investigate. The issue is that Firefox doesn't apply `font-weight: bold` to `strong` tags (which is a total nonsense).
I'll force this in Bay CSS and release an updated version.

**Comment by eliottvincent** [comment]
Here you go: https://github.com/eliottvincent/bay/releases/tag/v1.0.19

I confirm this fixes your issue.

**Comment by vischia** [comment]
It works like a charm! I didn't know Firefox had this kind of behaviour!

Thanks a lot for the prompt action!

Cheers,
Pietro
