### ISSUE TITLE
[Feature request] Is it possible to add out of the box support for a favicon? 

### ISSUE THREAD

**Issue by aligg** [eliottvincent/bay#25]
Hey there, 

Thanks for making the great jekyll template. Is it possible to add support for adding a favicon? Or in the case it exists already - how do I add one? 

Thank you!
-Ali

**Comment by eliottvincent** [comment]
Hey Ali!

You simply need to add a `favicon.ico` file in the root folder of your website.
For example this is the folder of my personal website, which uses the Bay theme:

![Screen Shot 2023-04-12 at 09 39 00@2x](https://user-images.githubusercontent.com/24720375/231386915-b573c5cc-f8fb-4fcf-886e-644224d9f22e.png)

**Comment by aligg** [comment]
Thank you! I added a favicon.ico file yesterday so let me see if it works!
