### ISSUE TITLE
Adding a new icon in footer

### ISSUE THREAD

**Issue by sklee2014** [eliottvincent/bay#26]
Hi! Thank you for your great work.

I just built a website following the instruction in "start from a clean website".

I'm wondering if I can add a new icon in the footer. If possible, can I know how to do it?

Thanks!

**Comment by eliottvincent** [comment]
Hey!

You are referring to this part, right?
![Screen Shot 2023-06-14 at 21 18 19@2x](https://github.com/eliottvincent/bay/assets/24720375/30e5bfde-7d10-4255-965a-549545d8604e)

In that case, it's easy. For example, if you want to add a link called `Acme`, then you need to edit the `config.yml` file and add your link there:

```markdown
footer:
  show_powered_by: true
  contact:
    ...
  follow:
    - name: Twitter
      link: http://twitter.com/YourTwitterUsername
      username: "@YourTwitterUsername"
    ...
    - name: Acme
      link: https://acme.com/
```

For the icon, you need to add a .png file in `/assets/img/icons/acme.png`

**Comment by sklee2014** [comment]
Oh, it's really easy to follow!

Thank you for your kind instructions!
