### ISSUE TITLE
Remove "follow" if empty

### ISSUE THREAD

**Issue by leandrochiarini** [eliottvincent/bay#31]
Hi there,

Thanks for the awesome template. I was wondering if it is possible to remove the "follow" section on the footer.  Is there a `show_follow` option?

**Comment by eliottvincent** [comment]
Hey, thanks for the kind words! I could hide the section if your `follow` array in `_config.yml` is empty. Would that suit you?

**Comment by eliottvincent** [comment]
I've pushed version 1.0.20! https://rubygems.org/gems/bay_jekyll_theme

Funny enough, the previous version, 1.0.19, was released exactly one year ago :)

**Comment by leandrochiarini** [comment]
Perfect! Thanks for the quick answer and for the great template!
