### ISSUE TITLE
What version of Ruby to use

### ISSUE THREAD

**Issue by polarcue** [eliottvincent/bay#40]
ruby-version: '3.1'：
listen-3.2.1 requires ruby version >= 2.2.7, 

 ruby-version: '2.7'：
![Screenshot 2024-05-21 at 18-54-39 Bay Jekyll Theme](https://github.com/eliottvincent/bay/assets/112614345/71c85fb8-6641-4a61-9912-4de3a003514e)

**Comment by eliottvincent** [comment]
Hello, I use `ruby 2.7.7p221`

What is your issue?

**Comment by polarcue** [comment]
css didn't work ,help
![屏幕截图(79)](https://github.com/eliottvincent/bay/assets/112614345/995afca5-533c-4ac2-9b25-3a8adf49dde9)

**Comment by eliottvincent** [comment]
Your CSS path is wrong. Simply follow instructions from the README and it will work :)
