### ISSUE TITLE
Email Button in Contact Footer

### ISSUE THREAD

**Issue by bricktoast** [eliottvincent/bay#46]
Hello!

Thank you so much for building this theme, I like it a lot.

I was wondering where the Email button in the footer should eventually link to? I see right now in my preview that the word Email is hyperlinked, but I cannot figure out how to get the value out of this link. I have the value typed into my _config.yml

I also looked on your personal site (in screenshot) and I'm not sure how to find what is linked there. 

<img width="237" alt="Screenshot 2024-10-23 at 9 24 24 PM" src="https://github.com/user-attachments/assets/df68716e-80fd-4739-8e90-121be2d861d1">

My next idea is to just replace the word "Email" with my actual email address.

Thank you ! :)

**Comment by eliottvincent** [comment]
Hey Megan!

> I was wondering where the Email button in the footer should eventually link to?

You can change the value of the link via your _config.yml, see screenshot:

![Screen Shot 2024-10-24 at 09 56 51@2x](https://github.com/user-attachments/assets/e6961650-7024-4abf-ab20-a374ecb3f766)

> but I cannot figure out how to get the value out of this link

That's normal, the email is "cloaked" / protected, meaning that the actual value is kind of hidden in the DOM, into multiple pieces. Then when a user clicks on your link, all the parts are retrieved, and the correct email value is generated. This is to avoid bots and scrappers to get your email by scrapping your website (and then sending you spam emails).

![Screen Shot 2024-10-24 at 10 05 58@2x](https://github.com/user-attachments/assets/cd3654f3-cf74-4244-afe4-55a431ac3039)

If you want to disable this feature, simply add `cloak: false` to the `contact` part of your config file. In that case, your email will be visible in the HTML. I wouldn't recommend that though.

Let me know if that's clear enough!

Eliott

**Comment by bricktoast** [comment]
Hi Eliott!

Thanks so much for your reply. I tried it on a different computer and was
able to get through to the email value on a Windows computer using Firefox,
but I'm unable to open it on a Macbook using Google Chrome. I'm not really
sure what's causing that, but wanted to let you know.

Thank you again!
-Megan

**Comment by eliottvincent** [comment]
So if I understand correctly, you click on "Email" but nothing happens. Interesting.
I just tried on my MacBook + Chrome and it works fine. 

Are you trying on https://eliottvincent.com/? Or your own website that uses the Bay template?

If possible, I'd like to have a screenshot of your browser's dev console when you click on the "Email".

**Comment by bricktoast** [comment]
Hi,

Yes, I took a screen recording with the console open.

**Comment by eliottvincent** [comment]
Ok, can you send it here please? :)

**Comment by bricktoast** [comment]
Sorry about that! I think the github to email client did not allow
attachments. Here is a drive link:
https://drive.google.com/file/d/1YNODkY9jZDI4iwNhNoC7G7JVmWDDZsLO/view?usp=sharing

**Comment by eliottvincent** [comment]
I don’t really know what’s happening sorry, I tried to reproduce but can’t.
I’d advise disabling the cloak feature :)

e.
