### ISSUE TITLE
Allow for longer link names in footer

### ISSUE THREAD

**Issue by emmacarli** [eliottvincent/bay#5]
Hello, more of a question than an issue, I have no experience in this so I'm not sure how to fix it myself.
How can I make the "Follow" section in the footer slightly wider to allow for longer link names, please?
![image](https://user-images.githubusercontent.com/39613453/103639110-23b46380-4f4e-11eb-8a84-0a4cb9a6a126.png)
I would be happy with just reducing margin size.
Thank you for your time!

**Comment by eliottvincent** [comment]
Hello @emmacarli , this is definitely something I can improve right in the theme! I'll issue a fix in the coming days.

**Comment by eliottvincent** [comment]
Hey, I've reworked the footer CSS in version **1.0.16**, this should fix the issues you have :)

**Comment by emmacarli** [comment]
Thank you, looks great!
